<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <section name="gallio" type="Gallio.Runtime.GallioSectionHandler, Gallio" />
  </configSections>

  <runtime>
    <!-- Don't kill application on first uncaught exception.
         We don't want the test runner to terminate itself unexpectedly
         without reporting the test failure associated with that exception. -->
    <legacyUnhandledExceptionPolicy enabled="1" />

    <!-- Enable loading assemblies over the network in .Net 4.0 -->
    <loadFromRemoteSources enabled="true" />
  </runtime>

  <system.runtime.remoting>
    <customErrors mode="off"/>
  </system.runtime.remoting>
  
  <system.diagnostics>
    <assert assertuienabled="false" />
  </system.diagnostics>

  <startup>
    <supportedRuntime version="v4.0.30319" />
    <supportedRuntime version="v2.0.50727" />
  </startup>
</configuration>
